[package]
name = "biased_fiber_box_dem_bpm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
default-run = "biased_fiber_box_dem_bpm"

[dependencies]
grass_app.workspace = true
tangle_app.workspace = true
tangle_characterize.workspace = true
tangle_core.workspace = true
tangle_export.workspace = true
tangle_generate.workspace = true
tangle_relax.workspace = true
tangle_example_support = { path = "../tangle_example_support" }
clap = { version = "4.5", features = ["derive"] }
